### ISSUE TITLE
ModuleNotFoundError: No module named 'deviceserve'

### ISSUE THREAD

**Issue by panciunio** [FujiNetWIFI/fujinet-emulator-bridge#1]
Hi,
I can't start FEB because lack of module: deviceserver

`python3 netsio-hub.py
Traceback (most recent call last):
  File "netsio-hub.py", line 4, in <module>
    import deviceserver
ModuleNotFoundError: No module named 'deviceserver'` 

Could you please advice me where I may find this module?

Regards,
pancio

**Comment by peterkaczorowski** [comment]
> $ python3 netsio-hub.py
> Traceback (most recent call last):
>   File "/Users/piotr/tmp/fujinet-emulator-bridge/fujinet-bridge/netsio-hub.py", line 4, in <module>
>     import deviceserver
> ModuleNotFoundError: No module named 'deviceserver'

Follow the instruction...  

You should copy "netsio-hub.py" to the Altirra/extras/deviceserver directory.  There is a file "deviceserver.py" In that directory.

Then it works.

For quick help/support please find us on "FujiNet User's Group" @ Facebook or at Fujinet @ Discord.

**Comment by a8jan** [comment]
readme was updated with instruction to change to Altirra/extras/deviceserver directory prior starting netsio-hub.py
