### ISSUE TITLE
module error in Altirra 4.0

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [FujiNetWIFI/fujinet-emulator-bridge#2]
netso.atdevice(266,21): Cannot call `sleep` at is can suspend, which is not supported by the current context

This message is show after run Altirra 4.0.
fujinet-emulator-bridge is updated to newer version.

**Comment by a8jan** [comment]
There was a workaround for Altirra 3.90 in netsio.atdevice and it worked for 3.90 and 4-test releases. With 4.0 final release it stopped to work.
I removed 3.90 workaround, so atdevice works now with Altirra 4.0
I will prepare extra version of atdevice for Altirra 3.9x.
